#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/carpentry-instructor-training/instructor-training-session-template"
workshop_site   : "http://carpentry-instructor-training.github.io/instructor-training-session-template"
#--------------------------------------------------------------------------------
# Standard Carpentry Instructor Training settings - should not need to be modified.
#--------------------------------------------------------------------------------
cti_contact     : "training-help@software-carpentry.org"
cti_github      : "https://github.com/carpentry-instructor-training"
cti_githumio    : "http://carpentry-instructor-training.github.io/"
cti_curriculum  : "http://swcarpentry.github.io/instructor-training/"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "http://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "http://files.software-carpentry.org"
swc_github      : "http://github.com/swcarpentry"
swc_githubio    : "http://swcarpentry.github.io/"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"
swc_twitter     : "http://twitter.com/swcarpentry"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#--------------------------------------------------------------------------------
# Standard Data Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
dc_blog        : "http://www.datacarpentry.org/blog/"
dc_contact     : "info@datacarpentry.org"
dc_github      : "https://github.com/datacarpentry"
dc_githubio    : "http://datacarpentry.github.io/"
dc_site        : "http://datacarpentry.org"
dc_twitter     : "http://twitter.com/datacarpentry"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
